# Site settings
title: Yi Zheng
description: Homepage
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://yizheng.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yi Zheng
user_description: Yi graduated from the University of Washington, Seattle in 2016 with a B.S. in Computational Mathematics (Algorithms) and a minor in Mathematics.
                  While at college, he was Vice President of CSSA and in charge of software, website development and video production.
                  Passionate about coding and its possibilities, Yi is currently employed by the Ohio Film Group and he provides his knowledge to help streamline work processes 
                  and improve workflows at OFG.
user_title: Software Engineer
email: yizheng0831@gmail.com
linkedin_site: https://www.linkedin.com/in/yizheng0831/
github_site:  https://github.com/qpskcn1
instagram_site:  https://www.instagram.com/qpskcn1/

# Google-analytics
google-analytics:
  id: "UA-61178393-2"

exclude: ['package.json', 'src' , 'node_modules']
